# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- 'feature-ms-eduardoAvello-mensaje'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      testResultsFiles: '**/TEST-*.xml'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloudConnection'
      organization: 'your-organization'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'your-project-key'
      cliSources: 'src'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'

  - task: Docker@2
    inputs:
      containerRegistry: 'your-container-registry'
      repository: 'your-container-repository'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

